# Generated by Django 6.0.3 on 2026-05-01 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='otpchallenge',
            new_name='api_otpchal_verific_b0bc5b_idx',
            old_name='otp_verif_idx',
        ),
        migrations.RenameIndex(
            model_name='otpchallenge',
            new_name='api_otpchal_email_0c3f3d_idx',
            old_name='otp_email_pur_idx',
        ),
        migrations.RenameIndex(
            model_name='otpchallenge',
            new_name='api_otpchal_expires_916a50_idx',
            old_name='otp_exp_idx',
        ),
    ]
